apps/core/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.views import PasswordResetView

from users.views import welcome

urlpatterns = [
    path("", welcome, name="welcome"),
    path("accounts/", include("users.urls")),
    path("admin/", admin.site.urls),
    path("metrics/", include("metrics.urls")),
    path("stats/", include("stats.urls")),
    path("docs/", include("docs.urls")),
    path(
        "password_reset/",
        PasswordResetView.as_view(
            email_template_name="registration/password_reset_email.txt",
            html_email_template_name="registration/password_reset_email.html",
        ),
        name="password_reset",
    ),
    path("", include("django.contrib.auth.urls")),
]

apps/docs/urls.py
"""Urls for docs"""
from django.urls import path

from . import views

app_name = "docs"

urlpatterns = [path("", views.ListView.as_view(), name="list")]

apps/metrics/urls.py
"""Urls for metric"""
from django.urls import path

from . import views

app_name = "metrics"

urlpatterns = [path("", views.ListView.as_view(), name="list")]

apps/stats/urls.py
"""Urls for stats"""
from django.urls import path

from . import views

app_name = "stats"

urlpatterns = [path("", views.store, name="store")]

apps/users/urls.py
"""Urls for user"""
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.welcome, name="welcome"),
    path("profile/", views.profile, name="profile"),
    path("register", views.register, name="register"),
]

apps/docs/models.py
"""Doc model"""
from django.db import models


class Doc(models.Model):
    """Docs model"""

    title = models.CharField(max_length=100)
    body = models.TextField()

apps/metrics/models.py
"""Metrics model"""
import numpy as np

from django.db import models


class Metric(models.Model):
    """Metrics model"""

    name = models.CharField(max_length=100)
    description = models.TextField()

    def stats(self) -> np.array:
        """Return numpy array of stats of model"""
        return np.array(self.stats)

    def mean(self) -> float:
        """Return mean of stats of metric"""
        return round(self.stats().mean(), 4)

    def std(self) -> float:
        """return standard deviation of stats of metric"""
        return round(self.stats().std(), 4)

apps/stats/models.py
"""Model for Stat"""
from django.db import models

from users.models import User
from metrics.models import Metric


class Stat(models.Model):
    """Model for Stat"""

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    metric = models.ForeignKey(Metric, on_delete=models.CASCADE)
    value = models.FloatField()

apps/users/models.py
"""Model file for user"""
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    """User model"""

    username = None
    email = models.EmailField(
        ("email"), unique=True
    )  # changes email to unique and blank to false
    api_key = models.CharField(max_length=500)
    metrics = models.ManyToManyField("metrics.Metric")

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = [""]

    def __str__(self):
        return self.email

apps/users/forms.py
"""Forms for user"""
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.utils.crypto import get_random_string
from .models import User


class UserCreationWithoutUsernameForm(UserCreationForm):
    """User creation form class. Uses email instead of username and no password confirmation"""

    username = None
    password2 = None

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields["password1"].help_text = "Min. 8 characters"

    def save(self, commit=True):
        if not commit:
            raise NotImplementedError(
                "Can't create User and UserProfile without database save"
            )
        user = super().save(commit=True)
        user.api_key = get_random_string(length=32)
        user.save()
        return user

    class Meta:
        """Meta class for User"""

        model = User
        fields = ("email",)


class UserWithoutPassWordConfirmationChangeForm(UserChangeForm):
    """User change form. Uses email and no password confirmation"""

    password2 = None

    class Meta:
        """Meta class for user"""

        model = User
        fields = ("email",)

apps/docs/views.py
"""Views for docs"""
from django.views import generic

from .models import Doc


class ListView(generic.ListView):
    """Index view"""

    context_object_name = "docs"
    model = Doc

apps/metrics/views.py
"""Views for metrics"""
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic

from .models import Metric


class ListView(LoginRequiredMixin, generic.ListView):
    """Index view"""

    context_object_name = "metrics"
    model = Metric

apps/stats/views.py
"""Views for stats"""
from django.shortcuts import get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse

from metrics.models import Metric
from users.models import User
from .models import Stat


@csrf_exempt
def store(request):
    """Allow users to post stats via `model.predict()`. Stores metric"""
    user = get_object_or_404(User, api_key=request.POST.get("api_key"))
    metric = get_object_or_404(Metric, name=request.POST.get("type"))

    if not user.metrics.filter(pk=metric.id).exists():
        user.metrics.add(metric.id)

    stat = Stat()
    stat.user_id = user.id
    stat.metric_id = metric.id
    stat.value = request.POST.get("stat")
    stat.save()

    return HttpResponse("")

apps/users/views.py
"""Views for user"""
from django.conf import settings
from django.core.mail import send_mail
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect

from .forms import UserCreationWithoutUsernameForm


def profile(request):
    """Profile page for user"""
    user = request.user
    return render(request, "users/profile.html", {"user": user})


def welcome(request):
    """Landing / user home page"""
    if request.user.is_authenticated:
        if request.user.stat_set.count() > 0:
            return render(
                request,
                "stats/stats_list.html",
                {
                    "user": request.user,
                    "stats": request.user.stat_set.all(),
                    "metrics": request.user.metrics.all(),
                },
            )
        return render(request, "users/home.html", {"user": request.user})
    return render(request, "users/welcome.html")


def register(request):
    """Register user"""
    if request.method == "POST":
        form = UserCreationWithoutUsernameForm(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data.get("email")
            raw_password = form.cleaned_data.get("password1")
            user = authenticate(email=email, password=raw_password)
            login(request, user)

            send_mail(
                "A new user registered",
                f"A new user with email {email} just signed up",
                settings.DEFAULT_FROM_EMAIL,
                [settings.ADMINS[0][1]],
                fail_silently=False,
            )

            return redirect("/")
    else:
        form = UserCreationWithoutUsernameForm()
    return render(request, "registration/register.html", {"form": form})

apps/docs/templates/docs/doc_list.html
{% extends "base.html" %}
{% block title %} Documentation {% endblock %}
{% block content %}

<div class="container">
    <div class="row justify-content-md-center mt-5">
        <div class="col-8">
            <h1>Documentation</h1>
            <p>
                Umpire is a machine learning monitoring tool that you can use to track how well your
                model is doing in production.<br>
                Add an umpire to your production code and see the results on your dashboard on this website.<br>
            </p>
            <p>
                Umpire currently only works with fastai v1.0.58 (or a few earlier versions). <br>
                Support for just Tensorflow (and Keras) or vanilla PyTorch will be added soon.
            </p>
            <p>
                <b>Overview</b><br>
                <ul>
                    <li><a href="#installation">Installation</a></li>
                    <li><a href="#setup">Setup</a></li>
                    <li><a href="#metrics">Metrics</a></li>
                </ul>
            </p>

            <h2 id="installation">Installation</h2>
            <p>
                <b>Conda</b><br>
                <code>
                    conda install umpire
                </code>
            </p>
            <p>
                <b>PyPI</b><br>
                <code>
                    pip install umpire
                </code>
            </p>

            <h2 id="setup">Setup</h2>
            <p>
                To start tracking your model performance with umpire, it needs:
                <ul>
                    <li>
                        a <a href="https://docs.fast.ai/basic_train.html#Learner">Learner</a> object
                    </li>
                    <li>
                        Your api key
                    </li>
                    <li>
                        a list of the metrics you want to track
                    </li>
                </ul>
            </p>
            <p>
                Let's run through an example. <br>
                <h5>0. Add required libraries</h5>
                <pre>
                    from fastai.basics import *<br>
                    from fastai.vision import *<br>
                    <br>
                    # Only needed in production environment, not during step 1<br>
                    from umpire import Umpire<br>
                </pre><br>
                <h5>1. Train a network</h5>
                <p>
                    First, set up your learner like you're used to do. In this example, we initialize a basic, resnet34 model with a subset of
                    MNIST as our data.<br>
                    If you already have a pretrained model, you can skip this step.
                </p>
                <pre>
                    data_path = untar_data('MNIST_SAMPLE')<br>
                    data = (ImageList.<br>
                    &nbsp;&nbsp;&nbsp;&nbsp;from_folder(data_path)<br>
                    &nbsp;&nbsp;&nbsp;&nbsp;.split_by_folder('train', 'test')<br>
                    &nbsp;&nbsp;&nbsp;&nbsp;.split_none()<br>
                    &nbsp;&nbsp;&nbsp;&nbsp;.databunch())<br>
                    <br>
                    learn = cnn_learner(data, models.resnet34)<br>
                    <br>
                    # we skip learning rate finder and freezing the model here<br>
                    learn.fit_one_cycle(5, 1e-02)<br>
                    learn.save('minst_sample_model')<br>
                    <br>
                </pre><br>
                <h5>2. Initialize umpire</h5>
                So you have a trained model that you want to use in production.<br>
                Let's use umpire to start tracking how well it is doing.<br>
                We will start with something simple and just track model confidence,
                but most of the umpire metrics are just as easy to add.
                <pre>
                    learn = load_learner('mnist_sample_model')<br>
                    <br>
                    learn = Umpire(api_key={your_api_key}).track(learn, metrics=['confidence'])
                    <br>
                </pre>
                <p>
                    Behind the scenes, umpire will add callbacks to your learner that will 
                    make sure you will track your model's confidence score.<br>
                </p>
                <h5>3. Use learner to predict something</h5>
                <pre>
                    from PIL import Image<br>
                    learn.predict(Image.open('path/to/image'))
                </pre>
                If you go to your umpire dashboard, you will see that umpire is tracking your model's confidence scores.
            </p>

            
            <h2 id="metrics">Metrics</h2>
            <p>
                <b>Confidence</b><br>
                Tracking model confidence tells you a lot about how good your model performs on your production data.
            </p>
            <p>
                <b>Pixel intensity</b><br>
                Pixel intensity can tell you how dark or light your images are on average.
            </p>
            <p>
                <b>Image size</b><br>
                Tracking the average image input size tells you something about the input your model deals with.
            </p>
            <p>
                <b>Model age</b><br>
                Model age tracks the age of the model file you're using to do the prediction.
                Adding this metric could be useful when you automatically retrain your model each n days, so you will know something went wrong when your model is older than these n days.
            </p>
            <p>
                <b>Logit min max</b><br>
                Logits can tell you more than just a softmax confidence value.
                Tracking logit min and max values is way to track how similar the outcomes of your production input are to the outcomes of your training data
                (<a href="https://arxiv.org/pdf/1905.09186.pdf" target="_blank">
                    Aigrain, Detyniecki, 
                    <em>Detecting Adversarial Examples and Other Misclassifications in Neural Networks by Introspection</em>
                </a>, figure 2).
            </p>
            <p>
                <b>Average logit value</b><br>
                Logits can tell you more than just a softmax confidence value.
                Tracking logit average value is a way to track how similar your the outcomes of your production input are to the outcomes of your training data.
            </p>
        </div>
    </div>
</div>

{% endblock %}

apps/metrics/templates/metrics/metric_list.html
{% extends "base.html" %}
{% block title %} Home {% endblock %}
{% block content %}

<div class="container">
    <div class="row justify-content-md-center mt-5">
        <div class="col-8">
            {% if metrics %}
                <p>
                    <b>
                        These are the available metrics you can track with umpire.<br>
                        More metrics and documentation will be added very soon.
                    </b>
                </p>
                {% for metric in metrics %}
                    <h5>
                        {{ metric.name|title }}
                    </h5>
                    <p>
                            {{ metric.description }}
                    </p>
                {% endfor %}
            {% else %}
                No metrics available
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

apps/stats/templates/stats/stats_list.html
{% extends "base.html" %}
{% block title %} Home {% endblock %}
{% block content %}
<div class="container-fluid">
  <div class="row justify-content-md-center">
    <div class="col-8 mt-5">
      {% for metric in metrics %}
        <div class="card">
          <div class="card-body bg-primary text-white py-2 pt-3">
            <h5 class="py-0">{{ metric.name|title }}</h5>
          </div>
          <div class="card-body py-1">
            <div class="row border-bottom mb-2">
              <div class="col-6">
                Mean: {{ metric.mean }}
              </div>
              <div class="col-6 text-right">
                Standard deviation: {{ metric.std }}
              </div>
            </div>
            <div class="card-text">
              <graph-component
                :stats="{{ metric.stats_list }}" 
                name="{{ metric.name|title }}"
              ></graph-component>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

apps/templates/base.html
{% load render_bundle from webpack_loader %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    {% load static %}
    <link href="https://fonts.googleapis.com/css?family=Karla:400,400i,700&display=swap" rel="stylesheet">
    
    {% include "partials/favicons.html" %}

    <title>Umpire | {% block title %}{% endblock %}</title>
  </head>
  <body>
    <div id="app">
      {% include "partials/navbar.html" %}
      <div id="content">
        {% block content %}{% endblock %}
      </div>
    </div>

    {% render_bundle 'main' %}
  </body>
</html>

apps/templates/base_email.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
</head>
<body>
    <style>
        {% include "partials/email.css" %}
    </style>
    <table class="wrapper" width="100%" cellpadding="0" cellspacing="0">
        <tr>
            <td align="center">
                <table class="content" width="100%" cellpadding="0" cellspacing="0">
                    <tr>
                        <td class="header">
                            <a href="/">
                                Umpire
                            </a>
                        </td>
                    </tr>

                    <!-- Email Body -->
                    <tr>
                        <td class="body" width="100%" cellpadding="0" cellspacing="0">
                            <table class="inner-body" align="center" width="570" cellpadding="0" cellspacing="0">
                                <!-- Body content -->
                                <tr>
                                    <td class="content-cell">
                                        {% block content %}{% endblock %}
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <table class="footer" align="center" width="570" cellpadding="0" cellspacing="0">
                                <tr>
                                    <td class="content-cell" align="center">
                                        Umpire
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</body>
</html>

apps/templates/partials/email_btn.html
<table class="action" align="center" width="100%" cellpadding="0" cellspacing="0">
  <tr>
    <td align="center">
      <table width="100%" border="0" cellpadding="0" cellspacing="0">
        <tr>
        <td align="center">
          <table border="0" cellpadding="0" cellspacing="0">
          <tr>
            <td>
            <a href="{{ protocol }}://{{ domain }}{{ url }}" 
              class="button button-blue" target="_blank">{{ text }}</a>
            </td>
          </tr>
          </table>
        </td>
        </tr>
      </table>
    </td>
  </tr>
</table>
  

apps/templates/partials/favicons.html
{% load static %}
<link rel="apple-touch-icon" sizes="57x57" href="{% static 'imgs/apple-icon-57x57.png' %}">
<link rel="apple-touch-icon" sizes="60x60" href="{% static 'imgs/apple-icon-60x60.png' %}">
<link rel="apple-touch-icon" sizes="72x72" href="{% static 'imgs/apple-icon-72x72.png' %}">
<link rel="apple-touch-icon" sizes="76x76" href="{% static 'imgs/apple-icon-76x76.png' %}">
<link rel="apple-touch-icon" sizes="114x114" href="{% static 'imgs/apple-icon-114x114.png' %}">
<link rel="apple-touch-icon" sizes="120x120" href="{% static 'imgs/apple-icon-120x120.png' %}">
<link rel="apple-touch-icon" sizes="144x144" href="{% static 'imgs/apple-icon-144x144.png' %}">
<link rel="apple-touch-icon" sizes="152x152" href="{% static 'imgs/apple-icon-152x152.png' %}">
<link rel="apple-touch-icon" sizes="180x180" href="{% static 'imgs/apple-icon-180x180.png' %}">
<link rel="icon" type="image/png" sizes="192x192"  href="{% static 'imgs/android-icon-192x192.png' %}">
<link rel="icon" type="image/png" sizes="32x32" href="{% static 'imgs/favicon-32x32.png' %}">
<link rel="icon" type="image/png" sizes="96x96" href="{% static 'imgs/favicon-96x96.png' %}">
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'imgs/favicon-16x16.png' %}">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="theme-color" content="#ffffff">

apps/templates/partials/navbar.html
<div class="container-fluid">
  <div class="row justify-content-md-center">
    <div class="col col-sm-12 col-md-10">
      <nav class="navbar navbar-expand-lg navbar-light">
          <a class="navbar-brand" href="/">
            <span class="font-weight-bold">Umpire</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <a href="{% url 'docs:list' %}" class="nav-link">
                  <button class="btn">Documentation</button>
                </a>
              </li>
              {% if user.is_authenticated %}
                <li class="nav-item">
                  <a href="{% url 'metrics:list' %}" class="nav-link">
                    <button class="btn">Metrics</button>
                  </a>
                </li>
                <li class="nav-item">
                  <a href="{% url 'accounts:profile' %}" class="nav-link">
                    <button class="btn">Account</button>
                  </a>
                </li>
              {% else %}
                <li class="class nav-item">
                  <a href="{% url 'accounts:register' %}" class="nav-link">
                  <button class="btn btn-primary">Sign up</button>
                </a></li>
                <li class="class nav-item">
                  <a href="{% url 'login' %}" class="nav-link">
                    <button class="btn btn-outline-primary">Log in</button>
                  </a>
                </li>
              {% endif %}
            </ul>
          </div>
        </nav>
    </div>
  </div>
</div>

apps/users/templates/users/home.html
{% extends "base.html" %}
{% block title %} Home {% endblock %}
{% block content %}
<div class="container-fluid">
  <div class="row justify-content-md-center">
    <div class="col-8 mt-5">
      Here's how to start using umpire.
      <br><br>
      Install umpire:
      <div class="bg-dark text-white my-2 p-2">
        <samp>pip install umpire-ai</samp>
      </div>
      Then, try to use umpire for the first time with your api key.
      Your API key:<br>
      <div class="bg-dark text-white my-2 p-2">
        <samp>{{ user.api_key }}</samp>
      </div>
      Initiate umpire:
      <div class="bg-dark text-white my-2 p-2">
        <samp>
          import umpire-ai<br>
          umpire = Umpire(api_key='{{user.api_key}}')<br>
          model = umpire.track(model, model_name='my_model_name', metrics=['confidence'])
        </samp>
      </div>
      Your <code>model</code> should be the object you will use to do a prediction. It doesn't matter if this is a PyTorch or TensorFlow model.
      Umpire will figure out which one you are using.<br>
      Your <code>model_name</code> is just a string to describe the model you are monitoring.<br>
      Now, use your model to predict something and refresh this page to see the confidence.
      <div class="bg-dark text-white my-2 p-2">
        <samp>
          model.predict(img)
        </samp>
      </div>
    </div>
  </div>
</div>
{% endblock %}

apps/users/templates/users/profile.html
{% extends "base.html" %}
{% block title %} Profile page {% endblock %}
{% block content %}

<div class="container m-5">
  <div class="row justify-content-md-center">
    <div class="col-8">
      <h1>Profile page</h1>
      email: {{ user.email }}<br>
      API key: {{ user.api_key }}
      <div class="mt-3">
        <a href="{% url 'logout' %}">
          <button class="btn btn-primary">
            Log out
          </button>
        </a>
      </div>
    </div>
  </div>
</div>

{% endblock %}

apps/users/templates/users/welcome.html
{% extends "base.html" %}
{% block title %} ML Performance monitoring {% endblock %}
{% block content %}
<div class="container m-md-5 hero">
  <div class="row m-1 m-md-5 align-self-center">
    <div class="col-sm-12 col-md-8 mt-5">
      <h1>
        Performance monitoring of your machine learning product.
      </h1>
      <h4 class="mt-4">
        Start tracking model performance within minutes.
      </h4>
      <div class="col-sm-12 col-md-7 bg-dark text-white pt-2 pb-2">
        <samp>pip install umpire-ai</samp>
      </div>
    </div>
    <div class="col"></div>
  </div>
</div>
<div class="container">
  <hr class="m-1 m-md-5">
</div>
<div class="container m-1 m-md-5">
  <div class="row m-1 m-md-5 align-self-center">
    <div class="col-sm-12 col-md-10">
      <h3>Example</h3>
      Give Umpire your model and your api key, and it will hook into TensorFlow's or Pytorch's
      <code>model.predict()</code>.
      <div class="bg-dark text-white mt-2 p-2">
        <samp>
          import umpire-ai<br>
          umpire = Umpire(api_key={my_api_key})<br>
          model = umpire.track(model, metrics=['confidence'])
        </samp>
      </div>
      <div class="pt-2">
        <a href="{% url 'docs:list' %}" class="text-link">Read the documentation</a>
      </div>
    </div>
  </div>
  <div class="container"><hr class="m-1 m-md-5"></div>
  <div class="row mt-2 mt-md-5 mx-1 mx-md-5">
    <div class="col-12 col-md-4"></div>
    <div class="col-12 col-md-8">
      <h3>Built with privacy in mind</h3>
      <div class="pt-md-2">
        Umpire only stores the final metrics you want to track,
        so it will never be able to know more than you want about your model. <br>
        All of our machine learning code is open source, so you can verify that you can trust us.<br>
        <a href="" class="text-link">
          <i class="fab fa-github"></i> Umpire's GitHub
        </a>
      </div>
    </div>
  </div>
  <div class="container"><hr class="m1 m-md-5"></div>
  <div class="row mb-2 mb-md-5">
    <div class="col-12 text-center">
      <a href="{% url 'accounts:register' %}">
        <button class="btn btn-lg btn-primary">
          Sign up
        </button>
      </a>
    </div>
  </div>
</div>
<div class="container-fluid bg-primary">
    <div class="row">
      <div class="col-12 text-white text-center pb-3 pt-3">
        Made in Amsterdam
      </div>
    </div>
  </div>
</div>
{% endblock %}